name: hopeful_gregory
services:
  main_app:
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 6045M
    environment:
      - ALLOW_FLIGHT=true
      - ENABLE_COMMAND_BLOCK=true
      - EULA=true
      - ICON=https://cdn.icon-icons.com/icons2/2699/PNG/64/minecraft_logo_icon_168974.png
      - INIT_MEMORY=1G
      - MAX_MEMORY=5G
      - MAX_PLAYERS=5
      - MOTD=Our little Minecraft Server
      - OPS=DadoSpeedy
      - OVERRIDE_ICON=TRUE
      - SERVER_NAME=home_server
      - SNOOPER_ENABLED=false
      - SPAWN_PROTECTION=0
      - TYPE=FABRIC
      - VERSION=1.20.1
    image: itzg/minecraft-server
    labels:
      icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhUL2RO0NvJjKmiIEixsFjDU9oPfU-0iXIPS7wJQM&s
    ports:
      - target: 25565
        published: "25565"
        protocol: tcp
      - target: 24454
        published: "24454"
        protocol: udp
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/minecraft
        target: /data
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    container_name: ""
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhUL2RO0NvJjKmiIEixsFjDU9oPfU-0iXIPS7wJQM&s
  index: /
  port_map: ""
  scheme: http
  store_app_id: hopeful_gregory
  title:
    custom: Minecraft Fabric
